export function escapeHtml(value: string | null | undefined): string {
  if (!value) return '';
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export type ReportPointRow = {
  captured_at: string;
  latitude: number;
  longitude: number;
  accuracy_m: number | null;
  category: string;
  status: string;
  note: string | null;
  remarks: string | null;
  recommended_procedure: string | null;
  inspector_name: string | null;
  thumb_data_uri: string | null;
};

export type ReportHtmlInput = {
  projectName: string;
  generatedBy: string;
  generatedAt: string;
  counts: { defect: number; normal: number; note: number; openDefects: number };
  points: ReportPointRow[];
};

export function buildReportHtml(input: ReportHtmlInput): string {
  const rows = input.points
    .map((p) => {
      const img = p.thumb_data_uri
        ? `<img src="${escapeHtml(p.thumb_data_uri)}" alt="" width="64" height="64"/>`
        : 'Image unavailable';
      return `<tr>
        <td>${img}</td>
        <td>${escapeHtml(p.captured_at)}</td>
        <td>${p.latitude.toFixed(5)}, ${p.longitude.toFixed(5)}</td>
        <td>${p.accuracy_m ?? '—'}</td>
        <td>${escapeHtml(p.category)}</td>
        <td>${escapeHtml(p.status)}</td>
        <td>${escapeHtml(p.note)}</td>
        <td>${escapeHtml(p.remarks)}</td>
        <td>${escapeHtml(p.recommended_procedure)}</td>
        <td>${escapeHtml(p.inspector_name)}</td>
      </tr>`;
    })
    .join('');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>FlahaINSPECT report</title>
  <style>
    body { font-family: Segoe UI, sans-serif; font-size: 11px; color: #1a1a1a; }
    h1 { font-size: 16px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border-bottom: 1px solid #ddd; padding: 4px; vertical-align: top; }
    footer { margin-top: 16px; color: #555; }
  </style>
</head>
<body>
  <h1>Flaha Agri Tech · FlahaINSPECT</h1>
  <p>${escapeHtml(input.projectName)} · generated by ${escapeHtml(input.generatedBy)} · ${escapeHtml(input.generatedAt)}</p>
  <p>Defect ${input.counts.defect} · Normal ${input.counts.normal} · Note ${input.counts.note} · open defects ${input.counts.openDefects}</p>
  <table>
    <thead>
      <tr>
        <th>Thumb</th><th>Time</th><th>Coords</th><th>Acc.</th>
        <th>Cat</th><th>Status</th><th>Note</th><th>Remarks</th><th>Procedure</th><th>Inspector</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <footer>Confidential — Flaha Agri Tech</footer>
</body>
</html>`;
}
